name: Despliegue Continuo a InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Desplegar sitio vía FTP
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código fuente
        uses: actions/checkout@v4

      - name: Sincronizar archivos vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
          protocol: ftp
          port: 21
          timeout: 60000
          dangerous-clean-slate: false
